[workspace]
members = ["packetvar-derive"]

[package]
name = "g-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.16.0"
packetvar-derive = { version = "0.1.0", path = "packetvar-derive" }