[workspace]
members = ["packetvar-derive", "parser-derive"]

[package]
name = "g-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.16.0"
encoding = "0.2.33"
packetvar-derive = { path = "packetvar-derive" }
parser-derive = { path = "parser-derive" }