[package]
name = "basic-extension"
version = "0.1.0"
edition = "2021"
authors = ["WiredSpast"]
description = "A basic example extension"

[dependencies]
g-rust = { path = "../../.", version = "0.0.1-beta.3" }